sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 16
script:
  - yarn run test
  - yarn run lint
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
