sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 16
script:
  - yarn run test
  - yarn run lint
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: npm
  email: 'fe@mailonline.co.uk'
  api_key:
    secure: gCw1Fa6Hrd7aS7lzkWk4tFj0s2ZTShFqYXcJh+sB2u8h+CYUNP3T4MXADKsFk9VtekcMPLkNJpa8ibOxvHssfkI1nEfe8LPN7C+oH9eTP8G4HU8ii92mdUs8WWRwqISH0S0lZF0rBzJvHFXlrOQ+OozY7bi3pcancN3+lIu1g5pN0cVzUOoWypYXUEZpdThOtB0ak7+1N3Z7SZcCXuGa5gYjFOd99bjYGizZKPx2/9AyYShr7LU87HB/Oc7IEXm715MuJwLuG0N/NAbcPggS15RRoc1Kpv2mWwjZ0ZPyeIZNeRRUEyhpbd/hOMRV5t+Jsg38IHBuystrChGS70q9NUKJnkMgwbemt965aMm8+IwT9KGce3odJGuIadaOboW7PcID4iM+hg0XLha7p+bUeSGa9z01Ww1P+IJLdiAb8c3IAP/3PsLPUDMixqha3/dNbPP9TrNzWvWNkb9yJcPA7Rgrm3B/0mpLynvETY5dL5eTSSB2ZUsdRYAuO68U5Y1uZhiOdmW2YYXU/KNRftgcZBpiW4Fv4LtYY7I5ANNyQBhvV3ahTklT+G+IDf7O9Sx4zuiLg79PQ1fgz3jaDxOFybNZiqIc999zZ+u9Hnay4bskuk2sYWi9gRU4zgH7ui8zqmcCl06YqtcGcabvu0F3CCBMLqB4+4O8advR4XhUwEo=
